server.port=8085
spring.application.name=pivot-analytics

# PostgreSQL подключение
spring.datasource.url=jdbc:postgresql://localhost:5433/pivot_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Логирование SQL
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
