# PostgreSQL конфигурация с вашим именем пользователя
spring.datasource.url=jdbc:postgresql://localhost:5432/analytics_db
spring.datasource.username=klebedevich
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA настройки
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Логирование
logging.level.org.springframework.jdbc=DEBUG
logging.level.repository=DEBUG

# Сервер
server.port=8080